### ISSUE TITLE
[Refactor] Tasks tracker

### ISSUE THREAD

**Issue by SBoudrias** [SBoudrias/Inquirer.js#692]
This tickets will list tasks that need to be completed to wrap-up Inquirer's core refactor.

I would love to have your help and make this refactor a success! Please comment below and let me know if you want to take ownership of a task. You can also jump into the [gitter chat room](https://gitter.im/SBoudrias/Inquirer.js) and ping me over there if you get stuck.

Basic prompt core re-implementation PR is over at #688 and the initial refactoring scope was discussed on #685.

### Goals

1. Faster and smaller package
2. All prompt will work standalone
3. Public facing backward compatible API (`inquirer.prompt`)

Note: With standalone prompt, this mean we'll be able to release those as soon as they're ready.

#### Rewriting prompts

- [x] `input` prompt
  - [x] `default` option support
  - [x] `transformer` option support
- [ ] `number` prompt
- [x] `password` prompt
- [x] `confirm` prompt
- [x] `list` prompt
- [x] `checkbox` prompt
- [x] `expand` prompt
- [x] `editor` prompt
- [x] `rawlist` prompt

#### Infra

- [ ] Core
  - [x] Support prefix overwrite
  - [x] List pagination module
    - [x] Handle multiline options gracefully
    - [x] Support for separators
    - [ ] Truncate non-highlighted options? (maybe as a configuration option?)
- [ ] Performance
  - [ ] Setup automated performance regression check
  - [ ] Setup automated package size regression check
- [x] Support Node 6 (we want to use async/await)
  - [x] Add typescript?
  - [x] Add babel build step?
- [x] Rewrite documentation
- [ ] Better behavior for edge cases
  - [ ] Non interactives terminals (#495)
  - [x] Pipe support? e.g. `yes | command-using-inquirer`

#### Top level API

- [x] Re-implement `inquirer` package to use the new prompts API
- [ ] Create a demo package we can easily use with `npx`

### Breaking change tracker

Listing the "by design" breaking change introduced in the different packages. Regression outside those are likely bug in the re-implementation and would be fixed.

- `list` prompt is renamed to `select` to match HTML semantics.
- No more reactive (rx.js) interfaces
- No more `inquirer.ui`
- No more `this.async()` syntax to define asynchronous actions

------

Do leave comments to if you think some tasks should be added to the refactor backlog!

**Comment by dwieeb** [comment]
I will 100% help get Inquirer setup with TypeScript. That will be a good task to start off with for me.

Depending on the timeline of this refactor, we may want to consider targeting Node 8 as a minimum. Node 6 will reach end-of-life next April: https://github.com/nodejs/Release Node 8 will allow us to use async/await natively.

**Comment by SBoudrias** [comment]
Yeah, we'll see how much people contribute and how fast this move forward. But I'd like the refactor to be completed in a few months.

But anyway, by adding typescript, it'd be easy to support Node 6 no?

**Comment by dwieeb** [comment]
It'd be easy, but there are two issues: 1) Missing newer Node APIs and 2) The output to Node 6 is ES2016, so when new syntax is used, TypeScript has to do some pretty ugly transforms, which result in ugly stack traces.

But... those issues probably aren't big enough reasons not to support Node 6.

We can always support a minimum of Node 8 by "flipping the switch" and doing a major release. TypeScript will then output ES2017.

**Comment by felixfbecker** [comment]
+1 for TypeScript!

**Comment by pvdlg** [comment]
Should a way to write unit tests for apps build with Inquirer be aded in the refactoring? See #379 for a proposed API. 

Not being able to test your code is a blocker for me and prevent me to use Inquirer (I had to switch to [prompts](https://github.com/terkelg/prompts) that offer the [inject](https://github.com/terkelg/prompts#injectvalues) method but there is many Inquirer features that I miss). The issue #379 is also the most thumbed up in the issue tracker, so I imagine I'm not the only one in that situation.

Even if a complex API like the one described in #379 is out of this refactoring scope, that would be great if at a minimum:
- We had a simple function to inject answers in unit test. Inquirer would just skip prompting the user and would use each answer injected. It would still trigger the `onEachAnswer`, `onError ` and `onComplete` callbacks.
- We had access to function/state that would ultimately allow to develop a test module with the API described in #379.

**Comment by LitoMore** [comment]
+1 for TypeScript!

**Comment by SBoudrias** [comment]
I've worked on a new API for the core prompt interface on this branch https://github.com/SBoudrias/Inquirer.js/tree/feature/replace-new-core-with-hooks-like-implementation

It works pretty much the same way as react hooks and so far has been quite extensible to fit the needs of the prompts I've reimplemented. I'd like to gather feedback on that API. See refactors of the `input`, `password`, `confirm` and `select` prompts.

**Comment by frangio** [comment]
@SBoudrias The link is broken.

**Comment by SBoudrias** [comment]
Hey @frangio it's been merged to the master branch already.

**Comment by SBoudrias** [comment]
I'll close this ticket. The remaining tasks weren't blockers, and it's pretty much all done.

Release announcement for the new API is here https://github.com/SBoudrias/Inquirer.js/discussions/1214
